/*
 * scene.h
 *
 * Responsible for:
 * - handling objects
 * - handling properties
 * - creating vertex buffers
 * - handling models
 *
 */

#ifndef PEQUODENGINE_SCENE_H
#define PEQUODENGINE_SCENE_H
#include <memory>

#include "input/input_manager.h"
#include "physics_engine/physics_engine.h"
#include "pobject/manager.h"

namespace Pequod {

/**
 * @brief Universal abstraction around how worlds are created and modified
 *
 * Game scenes contain everything a renderer can need to draw to the screen.
 * There is no platform specific code and instead what it does is generate
 * different types of primitives that are specific. For example, for simple
 * shapes like cubes the primitives are only triangle vertices with color and it
 * can be generated by the application. Then the application can render it
 * however it likes(one by one or batched) and create the shaders required for
 * each primitive type
 *
 */
class GameScene {
 public:
  virtual ~GameScene() = default;
  GameScene();

  virtual void OnStart() = 0;
  virtual void OnFrame(double delta_t) = 0;  // delta time in ms
  virtual void OnTick(double delta_t) = 0;   // delta time in ms
  virtual void OnDestroy() = 0;

  bool GetCameraProj(glm::mat4x4&);

  std::vector<Primitive> GetPrimitives();
  std::vector<StaticVertex> GetStaticVertices();
  std::vector<UINT> GetStaticIndices();

  TextureAtlas& GetAtlas();

  float GetWidth() const;
  float GetHeight() const;
  void SetWidth(float);
  void SetHeight(float);

  void SetInputManager(InputManager*);

  void QuitScene();
  bool ShouldQuit() const;

  void SimulatePhysics(int steps);

  void ProcessOnFrame(float alpha);
  void OnTickBegin();

 protected:
  std::shared_ptr<PObjectManager> object_manager_ = nullptr;
  std::shared_ptr<PhysicsEngine> physics_engine_ = nullptr;
  kEntityId player_camera_ = -1;
  InputManager* input_manager_ = nullptr;

 private:
  float width_ = 0.0;
  float height_ = 0.0;
  bool should_close = false;
};

}  // namespace Pequod

#endif  // PEQUODENGINE_SCENE_H
